# Hermes provider environment example.
OPENAI_API_KEY=<REPLACE_ME>
HERMES_MODEL=${HERMES_MODEL}
HERMES_MODEL_MODE=${HERMES_MODEL_MODE}
HERMES_MODEL_CODING=${HERMES_MODEL_CODING}
HERMES_MODEL_REASONING=${HERMES_MODEL_REASONING}
HERMES_MODEL_FAST=${HERMES_MODEL_FAST}
# OBSIDIAN_API_KEY intentionally not stored on VPS (Windows-local only).
VPS_HOST=${VPS_HOST}
VPS_SSH_PORT=${VPS_SSH_PORT}
VPS_USER=${VPS_USER}
VPS_REMOTE_PORT=${VPS_REMOTE_PORT}
