# Hermes provider environment example.
OPENAI_API_KEY=
HERMES_MODEL=${HERMES_MODEL}
OBSIDIAN_API_KEY=
OBSIDIAN_LOCAL_PORT=${OBSIDIAN_LOCAL_PORT}
VPS_HOST=${VPS_HOST}
VPS_SSH_PORT=${VPS_SSH_PORT}
VPS_USER=${VPS_USER}
VPS_REMOTE_PORT=${VPS_REMOTE_PORT}
